### ISSUE TITLE
Enable this for specific users

### ISSUE THREAD

**Issue by terryupton** [picdorsey/craft-sidebarenhancer#7]
Would it be possible to build in a flag/setting to only enable this for certain users?

**Comment by nicholasodonnell** [comment]
Hi Terry,

I understand the desire for such a feature; that shouldn't be too hard. It will require me to write a migration though, as soon as I have time I'll add it.

Thanks for your input!

**Comment by terryupton** [comment]
Great. Thanks.

**Comment by TerraSkye** [comment]
will this be done trough permissions ?

**Comment by nicholasodonnell** [comment]
@TerraSkye I was thinking about doing it using permissions, but the plugin only shows for admin users - who (by default) have all permissions. I would hate to force developers to create a whole separate user group just for this plugin since it's meant to be as simple as possible. I'm thinking about creating a plugin setting where admins can opt-out of seeing the enhanced sidebar.

**Comment by nicholasodonnell** [comment]
I added a plugin setting (Settings > Plugins) that lets you toggle the enhanced sidebar for specific admins only:

![screen shot 2017-04-18 at 10 02 34 am](https://cloud.githubusercontent.com/assets/1912717/25134814/9b9ebd64-241e-11e7-9a6c-bee77ef3aaaf.png)

Hope this helps and thanks @terryupton for the suggestion!
